### ISSUE TITLE
 pipedrive sync with podio

### ISSUE THREAD

**Issue by sourabhconstacloud** [pipedrive/client-nodejs#100]
Hello
i am trying to sync  pipedrive  with  podio using node so i need help

**Comment by eerootsus** [comment]
Hullo,

I suggest you check out the `examples` directory in this repository to get you going.

Also a good place to get information is our developer corner https://developers.pipedrive.com. There you will find references and examples and detailed specs. And I also welcome you to join our developer community for discussions about more detailed questions you might have.

As there is no report of an issue with this library, I'm closing this ticket.

e
