### ISSUE TITLE
Usage with async/await

### ISSUE THREAD

**Issue by kopax** [pipedrive/client-nodejs#101]
Hi guys, I see you still use `callback` for async call.

I'd like to know if we can use `async/await` instead of CB, is there a lib we can use for that?

**Comment by gutiju** [comment]
Hi.

Yes, there are plans to do this (and some other enhancements) and priorities are under discussion. However and unfortunately we do not have an ETA yet. Please, see #81. Since this is a duplicate of that, I'm closing this issue.

**Comment by eerootsus** [comment]
Duplicate of #81
