### ISSUE TITLE
Error in Open API specification

### ISSUE THREAD

**Issue by svachmic** [pipedrive/client-nodejs#103]
This really is not a Node.js client issue, but I couldn't find a place to drop this. It seems like the Open API specification has an error, specifically:

```
[main] WARN  o.o.c.config.CodegenConfigurator - There were issues with the specification, but validation has been explicitly disabled.
Errors: 
	-attribute components.schemas.WebhookBadRequest.items is missing
```

Perhaps this could be a "documentation" issue, or it could be escalated to the API spec team? Anyway, hope it helps.

The specification in question is [here](https://developers.pipedrive.com/docs/api/v1/pipedrive-api.yaml). The documentation links this url [here](https://developers.pipedrive.com/docs/api/v1/#/) - section Open API 3.

**Comment by tot-ra** [comment]
Hey. I forwarded this info to the team that is working on swagger yml. 
You can report it in https://devcommunity.pipedrive.com/ if you see that its not fixed soon
Will close the issue meanwhile

**Comment by svachmic** [comment]
Thanks a lot @tot-ra ! Actually the Open API reference is completely off. It looks like somebody started doing it but left it half way through. The return types are `void` and do not reflect the reality.

**Comment by mykhailo-riabokon** [comment]
Hi @svachmic

First of all, thank you for trying Open API spec out, and reporting an issue. Indeed, the spec is not fully finished and creating SDK from it will not give you the expected result, but our goal is to make it work too.

For now, Open API spec can be used with Swagger UI, to call endpoints and see scopes. Or you can import it in Postman to create collection of requests, but it's not ready for creating SDK yet.  

Sorry for the inconvenience.

**Comment by svachmic** [comment]
Thanks for coming back to me @mykhailodorokhov - perhaps it would be good for the newcomers to mention that on the page where the Open API spec is mentioned. So that everyone has the heads up that the SDK generators will not work.
