### ISSUE TITLE
Is the subdomain required?

### ISSUE THREAD

**Issue by harmon25** [pipedrive/client-nodejs#107]
[In this documentation](https://pipedrive.readme.io/docs/core-api-concepts-about-pipedrive-api)  and PHP example they use the companies subdomain when making requests. 

However, this nodejs library does not require it when instantiating the client.

**Is the company subdomain required when using the REST API?**

I am building a client for Elixir, and just wondering if I should require a `company_domain` configuration option. 

Thanks!

**Comment by tot-ra** [comment]
Hey. Quick answer (with 30% certainty), need someone from infra to clarify this, but from what I understand, no, its not required, but it can improve performance. 

It depends if this company domain helps to routes packets to correct datacenter or not. You can try with and without and share the results :)

**Comment by ziimk** [comment]
Company subdomain is not required but is strongly recommended. So, `api.pipedrive.com` will work but as @tot-ra said, using a specific company domain will help route your requests to the correct datacenter a bit faster.

**Comment by harmon25** [comment]
Thanks for the quick responses!
I will allow subdomain as config option, but have default point to `api.pipedrive.com`.
