### ISSUE TITLE
Update Oauth documentation for token handling

### ISSUE THREAD

**Issue by kmuenze** [pipedrive/client-nodejs#110]
This was a comment on the original Oauth ticket so adding here since that is closed now.

Are there some examples of where/how we would do this using the node library:
> application code must take care of fetching, storing and refershing the tokens.

> oauth - whether the API token is to be used as OAuth bearer token instead of classic API key (default is false). When setting oauth to true your application code must take care of fetching, storing and refershing the tokens.

**Comment by RuTsEST** [comment]
We now how examples in the README as well as a "How to use" section as of version 10. Feel free to take a look!
