### ISSUE TITLE
It is no longer possible to update custom fields of resources

### ISSUE THREAD

**Issue by henry-all3dp** [pipedrive/client-nodejs#114]
With the introduction of the new controller entities in version 10 it appears that the update for custom fields is no longer supported as these fields are cleared before the actual update happens.

Example: `DealsController.updateADeal` will call `updateADealAction` that will only add a predefined list of properties to the update request.

Is there a way to update custom fields with version 10 of the pipedrive client?

**Comment by RuTsEST** [comment]
Hello. Thanks for your feedback. We are currently investigating this issue.

**Comment by RuTsEST** [comment]
Hey! This issue should be fixed soon in the PR #116

**Comment by chemitaxis** [comment]
@RuTsEST you have another PR, please review ASAP 😄  

We need to release a new integration in our product with Pipedrive CRM, and we don't want to release a new separate version of the package. Thank you so much for your time.

P.D.: Do you think is possible a refactoring of the code to enable promises?

**Comment by RuTsEST** [comment]
@chemitaxis Hey! Updated the package.
