### ISSUE TITLE
Regression in createANewWebhook(): "Failed to get user or company" error if no user_id passed

### ISSUE THREAD

**Issue by bradvogel** [pipedrive/client-nodejs#115]
(cross-posted from https://devcommunity.pipedrive.com/t/recent-pipedrive-api-regression-unable-to-create-webhook-without-user-id/2353)

We’re no longer able to create Pipedrive webhooks using createANewWebhook (or the endpoint https://developers.pipedrive.com/docs/api/v1/#!/Webhooks/get_webhooks) without providing the optional user_id field. The documentation (both here in the node library and in the developers.pipedrive.com site) states that the `user_id` is optional, but when omitted, the HTTP response returns the error message “Failed to get user or company”. We believe the API only recently started requiring the `user_id` parameter.

This can be easily reproduced using the developer documentation tool. Screenshot: 
<img width="2017" alt="Screen Shot 2020-02-26 at 3 02 25 PM" src="https://user-images.githubusercontent.com/821706/75396650-e309a980-58a9-11ea-9919-3879b3c14cc8.png">

**Comment by AndreasSaltsberg** [comment]
Hello, this has now been resolved.
