### ISSUE TITLE
Organizations.getAll only retrieving 100 organizations

### ISSUE THREAD

**Issue by jakepens71** [pipedrive/client-nodejs#12]
router.get('/', function(req, res) 
              {
                    var orgName = [];
                    var orgID = [];

                   pipedrive.Organizations.getAll({}, function(err, organization) 
                        {
	                    if (err) throw err;
	                   for (var i = 0; i < organization.length; i++) 
	                   {
	                     orgName.push(organization[i].name);
	      
	                    }
	    
	    
	                   res.json(orgName);
                         });
                 });

This only ever returns 100. My company has a lot of organizations. How can I get it to return more?

**Comment by jakepens71** [comment]
I figured it out. Did not see this one

              pipedrive.getAll('Organizatons', function (err, collection) {
                               / collection contains all Organizations
                });

Then it gets all the desired fields. Thanks

**Comment by martintajur** [comment]
Yep. Sorry for not responding any earlier — but I see you figured it out within the same day there. That's why we have getAll method, indeed.
