### ISSUE TITLE
updateADeal cannot update title

### ISSUE THREAD

**Issue by kkudose** [pipedrive/client-nodejs#125]
I'm unable to update the `title` of a `deal` using `pipedrive.DealsController.updateADeal`. The following example `input` results in a 400 Bad Request:
```
const input = { id: 11, title: 'test' }
```
The following example updates the `personId` correctly, but the `title` is not updated:
```
const input = { id: 11, title: 'test', personId: 22 }
```
I've also had no issues updating custom fields.

**Comment by RuTsEST** [comment]
@kkudose Released a new version
