### ISSUE TITLE
Person.getUpdates() not returning all changes

### ISSUE THREAD

**Issue by f-ribeiro** [pipedrive/client-nodejs#128]
I need to know when a Person was updated after a certain timestamp. However, whenever I use the method getUpdates() for a Person object, it does not return the latest changes made to a Person, if those changes were made to email, name or some custom fields.
Is there a different way to get these types of changes with this client that I'm not aware?

In the first screenshot is the changelog of a Person on Pipedrive, with some parts erased:
![Screenshot-from-2020-03-09-14-12-16 (1)](https://user-images.githubusercontent.com/52535425/76222492-8fd11880-6212-11ea-8dfb-afa34cf51bfc.png)

And here's the response of the same Person's getUpdates call, where only the Person creation and the organization edit are returned:
[ CollectionItem {
    id: false,
    object: 'personChange',
    timestamp: '2020-03-09 14:05:41',
    data:
     { id: [removed],
       item_id: [removed],
       user_id: [removed],
       field_key: 'org_id',
       old_value: null,
       new_value: [removed],
       is_bulk_update_flag: null,
       log_time: '2020-03-09 14:05:41',
       change_source: 'app',
       change_source_user_agent: [removed],
       additional_data: [Object] },
    save: [Function],
    remove: [Function],
    get: [Function],
    merge: [Function],
    duplicate: [Function],
    toObject: [Function],
    set: [Function] },
  CollectionItem {
    id: false,
    object: 'personChange',
    timestamp: '2020-03-05 15:10:03',
    data:
     { id: [removed],
       item_id: [removed],
       user_id: [removed],
       field_key: 'add_time',
       old_value: null,
       new_value: '2020-03-05 15:10:03',
       is_bulk_update_flag: null,
       log_time: '2020-03-05 15:10:03',
       change_source: 'app',
       change_source_user_agent: [removed],
       additional_data: [] },
    save: [Function],
    remove: [Function],
    get: [Function],
    merge: [Function],
    duplicate: [Function],
    toObject: [Function],
    set: [Function] } ]

**Comment by RuTsEST** [comment]
Hey! Thanks for the feedback. We'll start investigating this issue ASAP.

**Comment by RuTsEST** [comment]
@f-ribeiro You can use the new version of the client to get all of the updates about a person by its ID. 
For example: 
`const response = await pipedrive.PersonsController.listUpdatesAboutAPerson({id: 1});
console.log('response => ', response);
`

**Comment by f-ribeiro** [comment]
@RuTsEST yes, however it still returns the incomplete list of updates made to a Person:
{ success: true,
  data:
   [ { object: 'personChange',
       timestamp: '2020-03-09 14:05:41',
       data: [Object] },
     { object: 'personChange',
       timestamp: '2020-03-05 15:10:03',
       data: [Object] } ],
  additional_data:
   { pagination: { start: 0, limit: 100, more_items_in_collection: false } } }

**Comment by RuTsEST** [comment]
Hey @f-ribeiro! I created a PR (#137) that should add the functionality to see all changes. I wasn't able to recreate your issue so could you please check if that fixes your issue. Once confirmed, I'll release a minor version.

**Comment by f-ribeiro** [comment]
Hi @RuTsEST ,
If I pass the 'allChanges: true', it now returns all the changes that are shown in the changelog. You've fixed it!
Thank you very much for the help.
