### ISSUE TITLE
PersonsController.addAPerson response failed

### ISSUE THREAD

**Issue by AgustinQuetto** [pipedrive/client-nodejs#129]
Hi! I'm looking for add a person using the new client and my responses failed.

**This is my input:**
```
[
  contentType: 'Content-Type',
  body: {
    name: 'Sarasa sarasa',
    email: 'sarasa@gmail.com',
    phone: '1111111111'
  }
]
```

**My response is:**
```
{
  errorMessage: 'HTTP Response Not OK',
  errorCode: 400,
  errorResponse: '{"success":false,"error":"Name must be given.","error_info":"Consulta developers.pipedrive.com para obtener m\\u00e1s informaci\\u00f3n sobre el API de Pipedrive.","data":null,"additional_data":null}'
}
```

What's wrong? Thanks!

**Comment by AgustinQuetto** [comment]
If contentType is removed, it works fine. Please, fix it or update the doc.
Thanks.

**Comment by RuTsEST** [comment]
Hey! Thanks for the issue. The docs will be updated in the next version of the client.

**Comment by boehlerlukas** [comment]
Please update the docs accordingly :) I just spent 4 hours finding out why this won't work (🥇
