### ISSUE TITLE
addFile inputs are inconsistent with docs

### ISSUE THREAD

**Issue by lucianolxp** [pipedrive/client-nodejs#132]
The documentation for FilesController / addFile lists all parameters as camelCase, but in lines 170-175 of FilesController.js the form data is prepared assuming input parameters as snake_case:
```
// prepare form data
const _formData = {
    file: _fs.createReadStream(input.file),
    deal_id: input.deal_id,
    person_id: input.person_id,
    org_id: input.org_id,
    product_id: input.product_id,
    activity_id: input.activity_id,
    note_id: input.note_id,
};
```

**Comment by RuTsEST** [comment]
Hey! Yes, currently the docs are using camelCase while the actual SDK is using snake_case. I'll add a NB in README to make that clear.

**Comment by RuTsEST** [comment]
Released a version in which you can use either snake_case or camelCase in addFile method.
