### ISSUE TITLE
Add followers in bulk?

### ISSUE THREAD

**Issue by MelMacaluso** [pipedrive/client-nodejs#134]
Hi guys, any way to add followers in bulk?

I have a webhook on deal updated that is called every time a deal is updated, and a deal is updated every time I add a follower...supposedly if I add them in bulk I will just trigger the webhook (so the lambda function...) once! 

At the moment being I have a nasty:

```js
[...]
  for (const user of users) {
    const input = {
      id: dealId,
      userId: user.id,
    }
    try {
      await pipedrive.DealsController.addAFollowerToADeal(input)
    } catch (error) {
      throw new Error(`--- Users could not be added as followers to deal: ${dealId} ---`)
    }
  }
```

would be amazing to have instead...(providing it doesn't exist, but I couldn't find it...).

```js
try {
    await pipedrive.DealsController.addAFollowersBulk(ids)
} catch (error) {
    throw new Error(`--- Users could not be added as followers to deal: ${dealId} ---`)
}
```

**Comment by ziimk** [comment]
Hey, the only way is to add them one by one. Pipedrive API does not support bulk adding of followers.
