### ISSUE TITLE
FilesController.addFile: dealId invalid property

### ISSUE THREAD

**Issue by AgustinQuetto** [pipedrive/client-nodejs#135]
Hi! The doc says "dealId" but is deal_id.
dealId isn't works as property.

**Comment by RuTsEST** [comment]
Hey! Yes, the docs are currently misleading. It's got to do with the underlying generation. I'll add a clarifying note in the readme about that.

**Comment by RuTsEST** [comment]
Released a version in which you can use either snake_case or camelCase in addFile method.
