### ISSUE TITLE
FilesController.getDownloadOneFile does not work

### ISSUE THREAD

**Issue by lucianolxp** [pipedrive/client-nodejs#138]
the response from the `/files/{id}/download` api route is a file, but the sdk expects a JSON and tries to parse it, resulting in an error

https://github.com/pipedrive/client-nodejs/blob/ccd54f244b63f7e0bb9e87e55705fe9a8096b0b8/lib/Controllers/FilesController.js#L758

**Comment by ziimk** [comment]
This looks like a bug indeed. We'll be trying to get a fix out the door during next week

**Comment by mykhailo-riabokon** [comment]
Hi @lucianolxp 

Thanks for reporting this issue. It was fixed in 10.4.3.
