### ISSUE TITLE
Update organization's custom fields

### ISSUE THREAD

**Issue by joelluijmes** [pipedrive/client-nodejs#140]
Hey, with the v10.x lib how would I efficiently update the organization fields? As it appears from the docs I have to make a call for each custom field I want to update. Is this correct or am I missing some bulk operation?

With the v9.x lib I could just call updateOrganization and it would update all custom fields.

**Comment by SiimKirjanen** [comment]
Hey @joelluijmes


Unfortunately, there is no bulk update method for organization's custom fields in API at this moment.

**Comment by SiimKirjanen** [comment]
Hey again

Starting from version 10.4.2 you can use updateAnOrganization to update custom fields. There is also organization-update.js in examples so you can try it out.

**Comment by joelluijmes** [comment]
Great, thanks for the quick resolution!

**Comment by joelluijmes** [comment]
Hang on, can you also incorporate this in the other types (deals and person).

**Comment by ziimk** [comment]
Hey, support for [deals](https://github.com/pipedrive/client-nodejs/pull/116) and [persons](https://github.com/pipedrive/client-nodejs/pull/121) has been added already :)
