### ISSUE TITLE
Bulk update organization

### ISSUE THREAD

**Issue by joelluijmes** [pipedrive/client-nodejs#141]
Hey, I was wondering if it is possible to update multiple organizations with a single call to stay under the rate limiter?

**Comment by mykhailo-riabokon** [comment]
Hi @joelluijmes !

Unfortunately, there is no bulk update method for Organization in API at this moment. Feel free to check our public API reference https://developers.pipedrive.com/docs/api/v1/#!/Organizations for more details.
