### ISSUE TITLE
TypeScript types ?

### ISSUE THREAD

**Issue by cyril94440** [pipedrive/client-nodejs#146]
Hi there,
Is there any @types available for TypeScript?

Thanks

**Comment by Maxi98** [comment]
+1

**Comment by fabiotheo** [comment]
+1

**Comment by shierro** [comment]
+1

**Comment by baxevanis** [comment]
+1

**Comment by DenisButCheR** [comment]
Hello. Unfortunately currently, we don't have support for TypeScript types.  It's not in our backlog as well. You can always contribute to help us!

**Comment by boredland** [comment]
@DenisButCheR would you accept a PR that makes this a Typescript package?
