### ISSUE TITLE
Deprecated dependency: request has been deprecated

### ISSUE THREAD

**Issue by MikeKoval** [pipedrive/client-nodejs#147]
Pipedrive client uses deprecated "request" dependency https://www.npmjs.com/package/request
Do you have any plans to fix it?

**Comment by ziimk** [comment]
Hi, thanks for the comment. We are aware of the deprecation and are taking steps to implement an alternative in the [code generator](https://github.com/pipedrive/client-nodejs#contributing).

I cannot give you a specific timeline, though.

**Comment by RuTsEST** [comment]
Hey! Since the new version is released now I'll close this issue, we are no longer using the "request" dependency.
