### ISSUE TITLE
Deprecated endpoints

### ISSUE THREAD

**Issue by zedtrix** [pipedrive/client-nodejs#157]
Pipedrive has deprecated some endpoints, the library will be obsolete soon.

On 31 March 2021 we will remove the following endpoints:

GET /deals/find
GET /organizations/find
GET /persons/find
GET /products/find
GET /searchResults
GET /searchResults/field
In case you are using the above-mentioned API endpoints in your code or 3rd party app/integration, please make sure to read the migration guide at https://pipedrive.readme.io/docs/new-search-api-migration-guide.

Some of the endpoints will be returning:

```
deprecation_warning: {
      '#': 'Warning! This endpoint will be removed soon. Please check API documentation at developers.pipedrive.com.'
    }
```

There is a plan to update the library?

**Comment by daniti** [comment]
Hi @zedtrix, thank you for pointing this out. Yes, in a future version these endpoints will be removed from the library.
