### ISSUE TITLE
Person update doesn't update organisation

### ISSUE THREAD

**Issue by rockrotem** [pipedrive/client-nodejs#158]
Hi,
On person update when I set new orgId it doesn't updated because these lines of code:
input.ownerId = undefined;
input.orgId = undefined;
input.visibleTo = undefined;

const _formWithDynamicFields = {...input, ..._form};

Why have you not updated these fields???

**Comment by rockrotem** [comment]
@SiimKirjanen Can you please take a look at this issue?

**Comment by DenisButCheR** [comment]
Hello @rockrotem . Can you please provide us more information on this topic? I just made a simple request and it worked perfectly for me.

`		const update = await lib.PersonsController.updateAPerson({
			id: 50,
			orgId: 1,
		});`

**Comment by RuTsEST** [comment]
Closing since the affected code has been updated in newer versions of the SDK.
