### ISSUE TITLE
Prefer POST requests using json instead of x-www-form-urlencoded

### ISSUE THREAD

**Issue by lucianolxp** [pipedrive/client-nodejs#159]
the official Pipedrive [openapi file](https://developers.pipedrive.com/docs/api/v1/pipedrive-api.yaml) uses mixed `content-type` for different POST or PUT endpoints:
- `application/x-www-form-urlencoded`: 46 places
- `application/json`: 152 places. 

On the other hand, Pipedrive also recommends using `json` for all requests ([link](https://pipedrive.readme.io/docs/core-api-concepts-requests))

The use of `x-www-form-urlencoded` on the SDK caused [this issue](https://devcommunity.pipedrive.com/t/link-sanitization-breaks-query-strings-with-the-character/3011/8)

As I understand, this SDK is generated from the openApi file, so a simple solution would be to update the openApi file first and then update the SDK

**Comment by RuTsEST** [comment]
Sorry for the long response. We have taken this issue to our backlog.

**Comment by SpaceOven** [comment]
Hi there!

It was changed to application/json where applicable. 👌
