### ISSUE TITLE
Clearing (custom) fields with null

### ISSUE THREAD

**Issue by kpala** [pipedrive/client-nodejs#162]
With version < 10 I was able to clear custom fields by using `null` values like this:

```
pipedrive.Deals.update(123, { %HASH%: null });
```

Trying to do the same with version >= 10 results now in a generic error 400 Bad Request. `undefined` value does not work either.

Looks like a workaround is to use an empty string for now, but this is not very intuitive and does not seem to be documented anywhere:

```
Pipedrive.DealsController.updateADeal({
    id: 123,
    %HASH%: ''
});
```

Retrieving the details of the deal after updating, the value corresponding to %HASH% is again `null`.

**Comment by RuTsEST** [comment]
Hey! 
Sorry for the delayed response. We'll look into it.

**Comment by youssef-saber-3** [comment]
Hey @kpala i looked into this issue with the latest version of the sdk and i couldn't reproduce it. i was able to clear custom fields using `null`

this works for me and i was able to clear this custom field. but using `undefined` doesn't work
 ``` 
const result = await api.updateDeal(1, 
         '772f94dd8f1fd9da1ea42720aa2985da938c57fc': null
})
```

let me know if you're still having issues with using `null` and i can try to debug it further

**Comment by youssef-saber-3** [comment]
i've tested this and it worked so i don't think there is an issue there. feel free to re-open it if you're still running into trouble with it
