### ISSUE TITLE
Deprecated PersonsController.findPersonsByName

### ISSUE THREAD

**Issue by EugenAz** [pipedrive/client-nodejs#163]
Hi guys,

I'm using `PersonsController.findPersonsByName` method which makes a request to a [deprecated API endpoint](https://developers.pipedrive.com/docs/api/v1/#!/Persons/get_persons_find). 

I could not find any other methods to search for Persons using this client.

When and how are you planning to update the client? 
Will you leave the method `findPersonsByName` backwards compatible switching the target API endpoint "under the hood"?

Thanks

**Comment by dmitriyeff** [comment]
Hi @EugenAz,

All new [search endpoints](https://pipedrive.readme.io/docs/changelog#removal-of-the-/find-/searchresults-and-/searchresults/field-endpoints-replaced-by-6-new-endpoints) were added in 10.5.0

https://github.com/pipedrive/client-nodejs/pull/180

**Comment by EugenAz** [comment]
Thanks for the update :+1:
