### ISSUE TITLE
New Search API migration 

### ISSUE THREAD

**Issue by noudard** [pipedrive/client-nodejs#168]
Hello,

Pipedrive team announced 6 new endpoints and the removal of 6 old endpoints with Search capability.
GET /deals/find
GET /persons/find
GET /organizations/find
GET /products/find
GET /searchResults
GET /searchResults/field

Do you plan to add a new controler to use the new ItemSearch ?

Best regards

**Comment by tw1t611** [comment]
Hey, I don't want to mess up the issue, but could you provide some information about the current state please?
The issue is about a month old.

**Comment by rybrad** [comment]
Would like to know this as well since the deprecation is only 2 months away.

**Comment by sbalaji1996** [comment]
+1 on this; the deprecation date is a month away. I noticed that the `v11` branch in this repository has the new search APIs:
- https://github.com/pipedrive/client-nodejs/blob/v11/src/api/ItemSearchApi.js
- https://github.com/pipedrive/client-nodejs/blob/v11/src/api/PersonsApi.js#L1117-L1183

Any chance we could get a release date for the `v11` version of this client?

**Comment by dmitriyeff** [comment]
@noudard thank you for paying attention to this issue. All new search endpoints were added in 10.5.0

Deprecated methods should be removed in the next major version.

https://github.com/pipedrive/client-nodejs/pull/180
