### ISSUE TITLE
Return the RateLimiting headers in metadata

### ISSUE THREAD

**Issue by lucianolxp** [pipedrive/client-nodejs#170]
with the rewrite in version 10 the feature of https://github.com/pipedrive/client-nodejs/issues/27 was lost

currently the headers information is never returned: just the response body is parsed and `_response.headers` is ignored, for example:
https://github.com/pipedrive/client-nodejs/blob/0467143b458b82109051e52a3c6efaa7306b35ee/lib/Controllers/DealsController.js#L928

we would like to write a backoff strategy for our application but it is not possible to do so with the current version of the sdk

**Comment by siirimangus** [comment]
Hey,
one possibility to get the headers, is to pass a callback function with three parameters to the request. The third parameter will include http context and you can extract the response headers from there. For example something like this:
```
const deals = await pipedrive.DealsController.getAllDeals(
    {start: 0, limit: 5},
    (error, response, context) => console.log('response headers', context.response.headers)
);
```
Would it work for you?

**Comment by lucianolxp** [comment]
Yes, that worked, thank you so much!
