### ISSUE TITLE
[question] client instantiation

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [pipedrive/client-nodejs#176]
Do I assume correctly that all auth configs are singletons and hence:
an application that manages multiple users / pipedrive installations needs to basically deep clone a `lib` object to not have side effects on the instances state?

**Comment by JSandmark** [comment]
I am also looking into this scenario as we run multiple Pipedrive apps backend with OAuth for multiple users and from some initial testing this lib does seem to be intended to work as a singleton. Does anyone use this lib for that scenario or do you use a custom API integration?
