### ISSUE TITLE
addAProduct doesn't set prices

### ISSUE THREAD

**Issue by 1valdis** [pipedrive/client-nodejs#178]
I'm trying to create a product with a price:
```javascript
const result = await pipedrive.ProductsController.addAProduct({ body: {
  name: 'Something',
  active_flag: false,
  prices: [ { currency: 'EUR', price: 123.45 } ],
}});
```
But the resulting product has empty `prices` array and doesn't have the price in the UI. What am I doing wrong?

**Comment by 1valdis** [comment]
If I make this same request, but with `active_flag: true`, the prices are set ccorrectly. So it looks like I can't set prices while creating inactive products? This is an unexpected behavior.

**Comment by RuTsEST** [comment]
Indeed, this seems unexpected, I've contacted the endpoint owners and hopefully this will get fixed in the near future.

**Comment by 1valdis** [comment]
Hey :) Thank you, better later than never, waiting for the resolution 👍

**Comment by RuTsEST** [comment]
Hey 👴.

The team responsible for the endpoint reached an agreement that they will not be implementing the functionality to set prices for soft deleted entities. 
If you want the product to not be findable in the search then you can set the "selectable" attribute to false.

Hope this helps!
