### ISSUE TITLE
Updating first_name fails

### ISSUE THREAD

**Issue by yaron-idan** [pipedrive/client-nodejs#18]
Hello,
First of all - thanks for the great API, so far it's working great, except for a glitch I just found when testing it around.
I am running the following code from my node app - 

`pipedrive.Persons.update(3908, {name: 'Loops333',first_name:'loop', last_name:'mull', email: 'loop@gmail.com'}, function(err){if (err) throw err;});`

The odd thing is that the email and name fields are updated, but the first_name and last_name fields remain the same.
If needed, I can attach more parts of the code and screenshots of the process.

Thanks,
Yaron.

**Comment by martintajur** [comment]
@mpukk You recently dealt with last_name and first_name with regards to how our public API handles updating them if they are given in an API request. What should be the expected behavior in the case shown above by @yaron-idan?

**Comment by mpukk** [comment]
Thanks Yaron for pointing that out.
And yes, that is a bug in the API. It should be possible to provide `name` or `first_name`+`last_name` combo and the other is filled in automatically. We'll probably get it fixed by the end of Q1 next year.

**Comment by martintajur** [comment]
Poking @mpukk , any updates on fixing this?

**Comment by mpukk** [comment]
Oh yes. It's fixed as of Feb 16th.
