### ISSUE TITLE
NotesController.addANote doesn't expect a "body" wrapper

### ISSUE THREAD

**Issue by manetrejo** [pipedrive/client-nodejs#181]
PersonsController.addAPerson and DealsController.addADeal methods receive input wrapped into a 'body' object:

`const person = { name: "John" };
const savedPerson = await pipedrive.PersonsController.addAPerson({ body: person });
`
But NotesController.addANote just expects the note object without the 'body' wrapper:

`const note={
        content: 'Test note',
        dealId: XXX
      };
const savedNote = await pipedrive.NotesController.addANote(note);
`

Shouldn't they behave the same way?

**Comment by RuTsEST** [comment]
Closing since the relevant code got changed in v11.
