### ISSUE TITLE
 [question] Is still pending LeadsController?

### ISSUE THREAD

**Issue by manetrejo** [pipedrive/client-nodejs#182]
Hi all,
I just want to know if LeadsController is unimplemented or just I need to set some flag during deals adding.

Thanks

**Comment by dmitriyeff** [comment]
Hello @manetrejo,

To perform the search from leads you can use `GET /itemSearch`. Here is the documentation: https://developers.pipedrive.com/docs/api/v1/#!/ItemSearch/searchItem

**Comment by manetrejo** [comment]
Perfect, this is what I'm doing now. I just asked if I could do this using the nodejs client.

**Comment by dmitriyeff** [comment]
Yes, you can do it using nodejs client, but new [search endpoints](https://pipedrive.readme.io/docs/changelog#removal-of-the-/find-/searchresults-and-/searchresults/field-endpoints-replaced-by-6-new-endpoints) (including itemSearch) were introduced in v10.5.0

[#180](https://github.com/pipedrive/client-nodejs/pull/180)
