### ISSUE TITLE
Adding production variations

### ISSUE THREAD

**Issue by rgraebert** [pipedrive/client-nodejs#20]
Hi,

I am trying to add a product_variation through the API. 
I call:
(1) getproduct
(2) attach product_varation to the retrieved product:
product.product_variations = [{ 
name : "OPTION1"
prices : [{
currency : "EUR"
price : 185
}],
product_id = PRODUCT_ID
}](3) I update product

Result: no product variations show up in the UI.

Could you provide a sample on how to create and update product variations? 

Thanks

**Comment by tot-ra** [comment]
Should be available in latest v6.0.3
