### ISSUE TITLE
Changing product price / removing a product currency

### ISSUE THREAD

**Issue by rgraebert** [pipedrive/client-nodejs#21]
Hi,

I am trying to update prices for products through the API. In the specific case I am struggling with, I am trying to change a product default price of 0 EUR to 299 USD. As this is a currency change, the API will actually add a scond price in USD. That is ok for me, but I could not find a way in the API to remove the EUR price. I can only do that through the UI.
I also tried with the API tester with and update the prices parameters to [{"currency":"USD", "price":299}] and nothing changed.

What is the correct way in the API to remove a currency / price?

Thanks

**Comment by eerootsus** [comment]
Although this is a very old issue I'm answering it for documentation reasons. And the answer which applies today would have been the same back then.

The current API does not support deleting a price - it can only be done in the UI. Existing currencies are updated and new ones added. So sadly there is no good programmatic approach at the moment. There are plans to rework the products feature and this will likely result in a better API feature set, but nothing solid yet.
