### ISSUE TITLE
Upload person picture, form-data issues

### ISSUE THREAD

**Issue by starman-vlad** [pipedrive/client-nodejs#223]
Hi,

I'm having trouble using the `addPersonPicture()` method as I can't figure out what type of binary data the `file` option accepts.

Following the docs on https://developers.pipedrive.com/docs/api/v1/Persons#addPersonPicture, I see that the `file` accepts `BINARY` data, but it seems that the method mentioned doesn't accept the raw binary image or encoded base64 images.

This is the sample code that I'm trying to use in order to upload the "Persons" picture
```js
router.post('/picture', async (req, res) => {
  try {
    const { id } = req.body;

    if (!id) throw new Error('Must include id');

    const { file } = req.files;

    // RAW binary
    const img = Buffer.from(file.data).toString();

    // base64 encoded
    // const img = Buffer.from(file.data).toString('base64);
    // `data:${file.mimetype};${img}`

    const user = await PersonsController
      .addPersonPicture({ id: Number(id), file: img });

    res.send(user);
  } catch (error) {
    res.status(400).send(error);
  }
});
```

I can see in the request that the form-data data is present (buffer).

I have tried to debug the "pipedrive" module, I see that it has issues with "path" (fs.createReadStream()). When I use the `base64` encoded image, the error is "name too long", but even with raw binary data from the form-data, it's still not working.

It doesn't work, no matter what I try. Could it be that it is because I'm using this with TypeScript? I personally highly doubt it, but I'm not sure.

**Comment by unigazer** [comment]
I believe the issue is because I'm not using the API through OAuth 2.0 protocol, but instead directly through the profile API key. Is it possible to use the `addPersonPicture` API without the OAuth 2.0 app? Is there a server-to-server communication for the given API?

**Comment by unigazer** [comment]
Found a workaround: https://developers.pipedrive.com/docs/api/v1/Persons#addPersonPicture
with a help of [How to forward a multipart/form-data POST request in Node to another service](https://stackoverflow.com/questions/53220350/how-to-forward-a-multipart-form-data-post-request-in-node-to-another-service)
