### ISSUE TITLE
Sandbox support

### ISSUE THREAD

**Issue by crebuh** [pipedrive/client-nodejs#228]
If checked the source code, but I cannot find a way to set the API endpoints to the sandbox environment. Is this a planned feature? Otherwise it would be pretty hard to work with this library in an enterprise application, where new feature have to be tested first inside the sandbox.

Any ideas on how to set the environment properly?

**Comment by RuTsEST** [comment]
Hey! We are planning to release a new version of the SDK in about a month where it would be possible to properly set the base path.
