### ISSUE TITLE
Bad request with {object}.save  ?

### ISSUE THREAD

**Issue by fabulousduck** [pipedrive/client-nodejs#24]
when i set a new value to a deal object and the execute the save function on it i get the following response : `[Error: Pipedrive API error:Bad request]`

Any idea as to why this may be happening ? 
code i am using below : 

```
deal.set(deal.value, updateValue)
deal.save(function handleSaveCallBack(err,data){
console.log('updatedValue : ', err, data)
})
```

**Comment by KGrey007** [comment]
I don't know if you are still having this issue, I just ran into it myself though.

I was able to solve it by string values into set. As if it wants actual JSON data to work with.
it ended up looking like

deal.set("status", "won");
deal.save(function(){
	console.log("saved...");
});

**Comment by fabulousduck** [comment]
Hey, I don't have the issue anymore (don't even work at the company i used it for anymore 😆 )

**Comment by tot-ra** [comment]
@fabulousduck I believe the problem is in line
`deal.set(deal.value, updateValue)`
The first argument is string key, so it should instead be 
`deal.set('value', updateValue)`
