### ISSUE TITLE
person_id 0 when set

### ISSUE THREAD

**Issue by fabulousduck** [pipedrive/client-nodejs#25]
When retrieving the person_id with getAll it is an object with multiple values.
but when i try to set it while creating a new Deal. it becomes 0 even though i passed in an object as a value ?

**Comment by tot-ra** [comment]
Sorry for late response, if its still relevant, can you please provide example code you tried?

**Comment by fabulousduck** [comment]
No. I don't even work at the company i used to work for who i was implementing this for haha.
But does this mean this package is being maintained again ?

**Comment by tot-ra** [comment]
Yes, check out pull requests to tag/contact responsible people. Closing this issue for now
