### ISSUE TITLE
searchOrganization response contains { custom_fields: NaN }

### ISSUE THREAD

**Issue by alex-all3dp** [pipedrive/client-nodejs#250]
When using `OrganizationsApi.searchOrganization()` the result item contains `{..., custom_fields: NaN }` where when using the API directly it correctly shows `{..., custom_fields: ["some string"] }`.

When debugging I noticed that `data` in https://github.com/pipedrive/client-nodejs/blob/f64d9eb393a9d603c99f4536352da0e0a187ac96/src/model/OrganizationSearchResponse.js#L53 correcly contains `custom_fields: ["some string"]` but after passing through `_OrganizationSearchResponseAllOf.constructFromObject()` it doesn't anymore.

Would greatly appreciate a fix :)

thank you!

**Comment by RuTsEST** [comment]
Thanks for the feedback, we'll take a look at it.
