### ISSUE TITLE
Cant use customFields which start with a numeric literal

### ISSUE THREAD

**Issue by christopherturinsky** [pipedrive/client-nodejs#251]
Unfortunately some of the custom Fields in the API-response start with a numeric literal (8fdc.....) which makes it impossible to read them.

`Parsing error: An identifier or keyword cannot immediately follow a numeric literal.`

Couldn't find anything in the docs if there is a workaround for that. Is that a known issue?

**Comment by IgnorancePulls** [comment]
Hello. Thanks for letting us know.
Could you please add more information under which circumstances you experienced this issue.
Steps to reproduce would also be helpful.

Thank you

**Comment by christopherturinsky** [comment]
Hey, sure! 

I think this isn't really a problem of the API but instead of how you assign ID's to custom values in the backend 🤔

No matter if I call the API with `getDeal(id)` / `getOrganisation(id`) or copy the API-Key from inside Pipedrive there are a lot of fields where the ID starts with a number.

<img width="303" alt="Bildschirmfoto 2021-11-17 um 13 46 44" src="https://user-images.githubusercontent.com/46715572/142203472-6e87e98a-d8d9-4a4e-b8bd-0186a8e101a5.png">

When I try to store the value inside a new variable after calling it with node or try to just log it I get the error I wrote above. For ID's which start with a-z its no problem to use them.
<img width="864" alt="Bildschirmfoto 2021-11-17 um 13 50 27" src="https://user-images.githubusercontent.com/46715572/142203934-06884cf7-5652-423f-8fc9-a0abed61f6b5.png">

Really wondering if nobody had that problem before or if there is a workaround.. Couldnt find anything online!

Thanks!

**Comment by 1valdis** [comment]
Hello @christopherturinsky  There's no problem with Pipedrive, there's a gap in your Javascript knowledge. To access any property of an object - including a property which begins with a number - you have to use index notation instead:
```javascript
const domains = product['84c5ce1b42...']
```
Using dot operator `something.property`, you can only access `property` which name follows certain rules, like not containing spaces and not beginning with a number.

**Comment by christopherturinsky** [comment]
Ahhh thank you, don know why I haven't tried this 🤦
