### ISSUE TITLE
Timezone of date fields

### ISSUE THREAD

**Issue by pcothenet** [pipedrive/client-nodejs#26]
The API / SDK returns date fields in this format:

``` Javascript
{
    update_time: '2016-10-13 15:20:06',
    add_time: '2016-09-30 16:54:18'
}
```

what time zone are those fields in? UTC? My account timezone?

Note: ISO strings would probably be a good idea for the API V2 :)

**Comment by martintajur** [comment]
Yes, all times given from the API are in UTC. Sorry about the non-ISO datestrings, it would indeed be easier to parse when given in ISO format! Definitely something to consider in the future.

**Comment by pcothenet** [comment]
Thanks!

**Comment by svachmic** [comment]
Hello, what is the status of this issue 3.5 years later? I've noticed that for custom fields the API returns some cryptic sub-custom fields that seem to hint at the support of timezones:

```
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": "15:30:00",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_until": "16:00:00",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_timezone_id": 327,
```

Does this mean timezones are supported? Can we get a list of the various timezones?
