### ISSUE TITLE
Return the RateLimiting headers in metadata

### ISSUE THREAD

**Issue by pcothenet** [pipedrive/client-nodejs#27]
AFAIK, the response from this SDK does not return the rate limiting info, right?

Would be great to add it in the response (along with pagination):

``` Javascript
  [
    [
        'results'
    ], 
        {
        pagination: {
            start: 0,
            limit: 500,
            more_items_in_collection: true,
            next_start: 500
        },
        rate_limit: {
            limit: x,
            remaining: xx,
            reset: xxx,
        }
    }
  ]
```

**Comment by martintajur** [comment]
You will be able to access request headers in the metadata with the 3.x version of the API client. The 3.x release is currently in review and will likely get merged in the next week or so. https://github.com/pipedrive/client-nodejs/pull/36

However the rate limiting data will be added not to the response additionalData block (as you gave the example) but instead it will be accessible from the callback's third argument, as in:
```
pipedrive.SearchResults.getAll(reqParams, function(err, searchResults, additionalData, meta) {
	console.log(meta.response.headers);
});
```

**Comment by martintajur** [comment]
Furthermore I have added a linear backoff strategy to the client itself, which honours the rate limiting headers given by the API server. That means you could rely on this logic and not worry about rate limiting on your own — or, alternatively, you can feel free to review the code in the pull request #36 and improve it as you like, then submit a pull request to us for review.

**Comment by pcothenet** [comment]
Awesome, that should work for me, thanks!

**Comment by martintajur** [comment]
Closing the issue for now, hoping to get 3.0 out soon.
