### ISSUE TITLE
rotten_flag on getStages is NaN

### ISSUE THREAD

**Issue by tomsjansons** [pipedrive/client-nodejs#311]
When calling the `getStages` in the client,  `rotten_flag` is `NaN` but while calling the API directly, it is returned as a boolean:
```json
{
  "id": 3,
  "order_nr": 2,
  "name": "Prospect Qualified",
  "active_flag": true,
  "deal_probability": 100,
  "pipeline_id": 1,
  "rotten_flag": false,
  "rotten_days": null,
  "add_time": "2022-02-15 12:08:28",
  "update_time": null,
  "pipeline_name": "Pipeline",
  "pipeline_deal_probability": false
}
```

I think the problem is coming from this line
https://github.com/pipedrive/client-nodejs/blob/fe53bf75cec70545526f89357bbbdce336fc7cd4/src/model/StageWithPipelineInfo.js#L87

Also the readme seems to suggest that `rotten_flag` is a number while in reality it's a boolean
https://github.com/pipedrive/client-nodejs/blob/master/docs/StageWithPipelineInfo.md

Same problem in [Open API 3 specification file](https://developers.pipedrive.com/docs/api/v1/openapi.yaml) on line 41407
https://developers.pipedrive.com/docs/api/v1/openapi.yaml

**Comment by ziimk** [comment]
Thanks! It was indeed wrong. Fixed in [13.2.8](https://github.com/pipedrive/client-nodejs/blob/master/CHANGELOG.md#1328)
