### ISSUE TITLE
Feature request: Support change of redirect URI with api or allow multiple

### ISSUE THREAD

**Issue by Jurajzovinec** [pipedrive/client-nodejs#318]
We will run concurrently two dashboard apps in our production environment (the old one and the remastered one) while we want to be able to authenticate via OAuth on both of them when installing the Pipedrive application. 
That means, we will need two redirect URIs for one app which seems like is not supported right now. 
A workaround would be to modify redirect URI dynamically via API. 

EXAMPLE:
*Situation*: Pipedrive application **FANCY_APP** has set redirect URI to **https://dashboard1-api.com/oauth-callback** 

*Complication*: User visits our new dashboard2 (which is doing basically the same as dashboard1 but has its own backend) and requests installation of **FANCY_APP** but in this case, we need to use **https://dashboard2-api.com/oauth-callback** as our URI

*Question*:  Will be endpoint **https://dashboard2-api.com/oauth-callback** get hit?

*Answer*: When the user asks for endpoint **https://dashboard2-api.com/install** we can trigger external API to Pipedrive in order to change redirect URI of **FANCY_API**. Therefore before the user will proceed to OAuth, we will make sure that he will not receive redirect URI do not match error.

**Comment by SpaceOven** [comment]
Hi @Jurajzovinec! 🙂 
Currently, we only support one redirect URL per app. There are no ongoing plans to allow additional ones.
