### ISSUE TITLE
`UpdateDealRequest` Converts `expected_close_date` to Date object but API expects an `ISO 8601 format: YYYY-MM-DD` string

### ISSUE THREAD

**Issue by zkirby** [pipedrive/client-nodejs#320]
https://github.com/pipedrive/client-nodejs/blob/fe53bf75cec70545526f89357bbbdce336fc7cd4/src/model/UpdateDealRequest.js#L102-L104

Not sure if there's any additional info that would be helpful - if so I'll make an addendum to this ticket!

**Comment by siirimangus** [comment]
Hey, @zkirby! Thank you for reporting. The issue should be now fixed starting from [version 13.3.1](https://github.com/pipedrive/client-nodejs/pull/325).
Closing this ticket.
