### ISSUE TITLE
PersonsApi#updatePerson should not require a name

### ISSUE THREAD

**Issue by danemauland** [pipedrive/client-nodejs#329]
Since a person can be uniquely identified with the id, which is already required, there is no reason to need the name of the person. In an asynchronous workflow, requiring the name can cause issues. For example, if a third party application tries updating a person whose name was just changed in Pipedrive but not yet reflected in the third party app, the update would incorrectly change the name back to the original value.

**Comment by siirimangus** [comment]
Hey, @danemauland, thank you for reporting. Yes you are correct, there is a mistake in our public documentation and also in the SDK. `name` should not be a required parameter. The fix is in our roadmap.

**Comment by SpaceOven** [comment]
Fixed on release [v14.0.1](https://github.com/pipedrive/client-nodejs/releases/tag/v14.0.1)
