### ISSUE TITLE
.getAll -> start: start is not defined.

### ISSUE THREAD

**Issue by Tylermarques** [pipedrive/client-nodejs#33]
In version 2.1.3 .getAll returns an error saying 'start' in Pipedrive.js in undefined. This error was fixed by reverting to 2.1.0.

**Comment by chyipin** [comment]
Submitted a PR (https://github.com/pipedrive/client-nodejs/pull/34) to fix this.

**Comment by Tylermarques** [comment]
Thank you!

**Comment by andrewkarell** [comment]
Merged into v2.1.4
