### ISSUE TITLE
Cannot find module '@babel/runtime/helpers/interopRequireDefault' on v13.3.2

### ISSUE THREAD

**Issue by yoagauthier** [pipedrive/client-nodejs#330]
Hi there,

It seems there is a dependency issue on [NPM package](https://www.npmjs.com/package/pipedrive) version 13.3.2

I've got the error `Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'`

Reverting to 13.3.1 or lower made the compilation possible.

**Comment by mcrstudio** [comment]
@siirimangus yeah, my application has thrown the same error.

**Comment by SiimKirjanen** [comment]
Hey. The issue was fixed in version 13.3.3

**Comment by thadeu** [comment]
Hey folks! The issue throw again in the v18 version.

Downgrade to v17.5.4 resolve for now. But I can't use v18.

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/77889/207672694-246b4090-54fd-4988-8a29-025feb1bbe47.png">

Can we reopen this issue?
