### ISSUE TITLE
Pipedrive `due_date` property can't be correctly set using SDK

### ISSUE THREAD

**Issue by zkirby** [pipedrive/client-nodejs#336]
https://github.com/pipedrive/client-nodejs/blob/3f6d88d18de2714729854dcf5d8d66d0a0053ec7/src/model/ActivityPostObject.js#L57-L59

I can't seem to be able to update the `due_date` using the SDK. I've tried a multitude of different formats but I believe the RC is actually that the API accepts a string and not a Date object in this parameter.

I've been able to verify this by calling the API without performing the provided SDK transform and setting `due_date` to be a string. When called in this manner, the API correctly sets the parameter.

**Comment by SiimKirjanen** [comment]
Hey. Yes indeed the API accepts `due_date` as a string (YYYY-MM-DD). https://developers.pipedrive.com/docs/api/v1/Activities#updateActivity
