### ISSUE TITLE
Old version of formidable in superagent 5.3.x has a critical vulnerability

### ISSUE THREAD

**Issue by rabbitfufu** [pipedrive/client-nodejs#341]
The version of superagent that is bundled contains an older version of formidable which Snyk is flagging as a having critical vulnerability.

https://security.snyk.io/vuln/SNYK-JS-FORMIDABLE-2838956

Would it be possible to have a release that packages an updated version of superagent / formidable?

ty

**Comment by siirimangus** [comment]
Hey, thank you for reporting! The `superagent` and `formidable` version bump was made in [v15.0.1](https://github.com/pipedrive/client-nodejs/releases/tag/v15.0.1).
