### ISSUE TITLE
Normalization of a custom monetary field currency causes an error

### ISSUE THREAD

**Issue by dchekanov** [pipedrive/client-nodejs#350]
We have a custom monetary field for deals. API requires to supply currency with the value like this (I believe):

```json
"3c25bf850df73fd26fb8367326d1465a59d931ca": 100,
"3c25bf850df73fd26fb8367326d1465a59d931ca_currency": "CHF"
```

This works fine when submitted with Postman, but this library converts "3c25bf850df73fd26fb8367326d1465a59d931ca_currency" into "3_c_25_bf_850_df_73_fd_26_fb_8367326_d_1465_a_59_d_931_ca_currency" and API won't accept it:

```
"3_c_25_bf_850_df_73_fd_26_fb_8367326_d_1465_a_59_d_931_ca_currency" is not allowed
```

**Comment by SiimKirjanen** [comment]
Hey. This issue should now be resolved

**Comment by dchekanov** [comment]
Thanks, it works now!
