### ISSUE TITLE
Update organization forcing name as required

### ISSUE THREAD

**Issue by marceloabk** [pipedrive/client-nodejs#354]
https://github.com/pipedrive/client-nodejs/blob/2582506cd777515e262c52f2bd1e479b51137bc3/src/api/OrganizationsApi.js#L1352

I think that requiring name at organization update is not making sense

**Comment by RuTsEST** [comment]
Fixed by #339

**Comment by marceloabk** [comment]
@RuTsEST I don't think that #339 is fixing the issue. The PR is entirely related to the Person API and the code I linked is still there.
