### ISSUE TITLE
getAll Activities only returns Activities related to user

### ISSUE THREAD

**Issue by Tylermarques** [pipedrive/client-nodejs#37]
Both Activities.getAll() and .getAll('Actitivities') only returns activities relating to the user whose API key is in use.

If this is intentional can it be made clear that this is how it is supposed to operate? 

Thanks,

**Comment by martintajur** [comment]
Set the `user_id` property to 0, as in:
```
pipedrive.Activities.getAll({ user_id: 0 }, function(err, list) {
	_.forEach(list, function(item) {
		console.log(item.subject);
	});
});```
This will do.
