### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by SiwakornSitti** [pipedrive/client-nodejs#39]
When I try to delete lots of products, I got this error.

**Comment by tot-ra** [comment]
Sorry for late response, if its still relevant, can you please provide example code you tried?

**Comment by divsbhalala** [comment]
@tot-ra I am using this library and creating fields async 2 at a time and I am also getting `socket hang up` error 
![image](https://user-images.githubusercontent.com/12185309/48768297-bf3ad980-ecde-11e8-95ca-a4e1aa636c7e.png)

**Comment by tot-ra** [comment]
@divsbhalala can you provide the code? what fields are you creating? custom fields?

**Comment by eerootsus** [comment]
Closing this issue as it's old and very likely no longer relevant to the initial reporters.
