### ISSUE TITLE
Client.getAll is broken

### ISSUE THREAD

**Issue by deathbearbrown** [pipedrive/client-nodejs#40]
Client.getAll method is broken. The wrong parameters variable is being passed in the recursive fetch function.

PR incoming :)

**Comment by dotdotdotpaul** [comment]
What was the result of the brokenness?  I tried using "pipedrive.Persons.getAll()" and I get 100 results back.  That's it, just 100 results, out of 29k.  It seems like the pagination isn't working.  Can't tell if this is the same issue or not.

I wrote my own code to specifically use the start and limit arguments and I got it to work that way, but I would really have loved not to have to do that...

**Comment by rohit12sh** [comment]
@dotdotdotpaul do you mind sharing your custom code? I am trying to fetch all records through pagination myself. Thank you in advance!

**Comment by dotdotdotpaul** [comment]
I'm not a great Javascript person, and had help from coworkers here who are better than I am, but we ended up with something like this:

```
  cachePeopleFoundInPipedrive() {
    return new Promise((resolve, reject) => {
      const perPage = 100;

      const doLoop = (page) => {
        const personQuery = {
          start: (page * perPage),
          limit: perPage,
          filter_id: 0 // We were using a custom filter from a config file.
        };

        this.client.Persons.getAll(personQuery, (err, collection) => {
          if (err) {
            return reject(new Error('Got error fetching Pipedrive Persons: ' + err));
          }

          // Here we would filter through the list and toss people into a cache we were building

          if (collection.length === perPage) {
            return Promise.resolve()
              .then(() => {
                doLoop.call(this, page + 1);
              });
          } else {
            resolve();
          }
        });
      };

      doLoop.call(this, 0);
    });
  }
```

**Comment by rohit12sh** [comment]
Thanks @dotdotdotpaul!
