### ISSUE TITLE
Cannot find module @babel/runtime/helpers/interopRequireDefault

### ISSUE THREAD

**Issue by thadeu** [pipedrive/client-nodejs#404]
Hey folks! The issue throw again in the v18 version.

Downgrade to v17.5.4 resolve for now. But I can't use v18.

### Other issues

#330
#321 

![image](https://user-images.githubusercontent.com/77889/207673086-a7184ddf-879f-4924-9783-6777acd754e0.png)

**Comment by RuTsEST** [comment]
Hey! 
Sorry for the runtime bug. I'll release a patch today. 
We'll look into putting systems in place to detect this automatically.

**Comment by RuTsEST** [comment]
Should be fixed with #406
