### ISSUE TITLE
Typo in OpenAPI document

### ISSUE THREAD

**Issue by rzuppur** [pipedrive/client-nodejs#407]
Document at https://developers.pipedrive.com/docs/api/v1/openapi.json `/itemSearch/field` response contains a key **`applicatoin/json`**

**Comment by bashmach** [comment]
Hi,
Thanks for reporting it. This seems to be already fixed:

![image](https://user-images.githubusercontent.com/333910/214492163-30a3454b-f20f-403a-8328-1c02d1732147.png)
