### ISSUE TITLE
Support the field selector

### ISSUE THREAD

**Issue by tschneid** [pipedrive/client-nodejs#42]
This is a feature request to support the field selector as described in the [Pipedrive API v1 reference](https://developers.pipedrive.com/docs/api/v1).

> **Field selector**
> You can pass in a field selector to indicate which fields you would like to fetch per each object when asking for a collection/list of objects. For example, you may only want to fetch deal's ID, title, value and currency when asking the deals list. This can be done by using the following syntax: `GET https://companydomain.pipedrive.com/v1/deals:(id,title,value,currency)?api_token=YOUR_API_TOKEN`.

Is there any way to use the field selector with the existing client? I tried the `pipedrive.getAll('Collection:(id)')` method, but this did not work.

**Comment by eerootsus** [comment]
@tschneid Thanks for bringing this up! Definitely would be a nice feature, but this is not supported at the moment and we don't have this on our roadmap either.

And deep apologies for such a later response.
