### ISSUE TITLE
deal.addProduct does not honor required fields

### ISSUE THREAD

**Issue by chemdrew** [pipedrive/client-nodejs#44]
if deal.addProduct does not contain the required fields it will return a success callback but without attaching the deal

```
deal.addProduct({` product_id: 23, quantity: 1, item_price: 0 }, (addErr, addData) => {
addErr = null
addData = [ CollectionItem {
    id: false,
    save: [Function],
    remove: [Function],
    get: [Function],
    merge: [Function],
    duplicate: [Function],
    toObject: [Function],
    set: [Function],
    getDeals: [Function] } ]
```
where item_price has to be defined and greater than 0 apparently. At least make this return in the error callback if id is false?

**Comment by tot-ra** [comment]
@chemdrew please check with latest version 3.0.2 if you receive an error
