### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by ChristopherNowlan** [pipedrive/client-nodejs#441]
./node_modules/formidable/src/Formidable.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/formidable/src/Formidable.js
./node_modules/formidable/src/index.js
./node_modules/superagent/lib/node/index.js
./node_modules/pipedrive/dist/ApiClient.js
./node_modules/pipedrive/dist/index.js

**Comment by ziimk** [comment]
Hey @ChristopherNowlan 👋 Can you please add steps to reproduce this issue? It's not immediately clear how this error occurred

**Comment by ChristopherNowlan** [comment]
@ziimk
