### ISSUE TITLE
Error handling is totally broken

### ISSUE THREAD

**Issue by khous** [pipedrive/client-nodejs#47]
When calling `pd.OrganizationFields.add` with some invalid arguments one would expect an error to be returned as the first argument of the callback.
This is not the case, I don't believe this is the case for any API method. Instead `err` is `null` and the rest of the arguments are empty objects.
It is incredibly frustrating as an API user to have silently failing API calls. Please see the attached image. As you can see, it's gotten to the default else case and will not emit an error.

![image](https://cloud.githubusercontent.com/assets/3698369/26472516/58c1437c-415b-11e7-919b-d61ccab315dc.png)

**Comment by deespater** [comment]
@khous we've fixed this issue in the latest package version 3.0.2
