### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by Tr1Galki** [pipedrive/client-nodejs#479]
Is it mistake at complete example?
`app.get('/callback', (req, res) => {
    const authCode = req.query.code;
    const promise = apiClient.authorize(code);
`
would it be correct to enter here?
`apiClient.authorize(authCode );`

**Comment by siirimangus** [comment]
Hey, @Tr1Galki , thank you for the sharp eye and reporting! Yes, you are correct, the variable name in the `authorize` method should be `authCode`. We fixed it in the [v20.5.2](https://github.com/pipedrive/client-nodejs/releases/tag/v20.5.2).

I will close the issue, cheers!
