### ISSUE TITLE
Fix "Prototype Override Protection Bypass" vulnerability

### ISSUE THREAD

**Issue by raphaelchampeimont** [pipedrive/client-nodejs#49]
Hello,

It seems that this package is vulnerable, see: https://snyk.io/test/npm/pipedrive/3.0.1

The vulnerability comes from the "qs" dependency, so I guess a simple solution would be to upgrade this dependency.

**Comment by JaakkoL** [comment]
This is still a valid issue with v.5.0.0 https://snyk.io/test/npm/pipedrive/5.0.0
