### ISSUE TITLE
New Project Endpoints

### ISSUE THREAD

**Issue by jaschaio** [pipedrive/client-nodejs#498]
Not really `client-nodejs` related but not sure if there is any other place to provide feedback?

First of all: Thanks for making project information available via the API.

But by testing I see quite a bit of limitations:

[Get all Projects](https://developers.pipedrive.com/docs/api/v1/Projects#getProjects)
I can not get a list of projects for a given deal_id. Instead I need to get a list of all projects and filter it on the client to find a project that has been associated with a given deal_id.

Introducing a `deal_id` query parameter would make this a lot easier and require less resources

[Get Details of a Project Template](https://developers.pipedrive.com/docs/api/v1/ProjectTemplates#getProjectTemplate)
This is returning the same thing as the List endpoint, just for a single Project Template.

Instead I would expect either here or as a seperate API resource the tasks that have been defined within a project template. Right now I can't get any info about template tasks as I would be able to get via the Pipedrive UI.

[Get all Deals](https://developers.pipedrive.com/docs/api/v1/Deals#getDeals) and [Get details of a Deal](https://developers.pipedrive.com/docs/api/v1/Deals#getDeal)
Project endpoints have been added, but it doesn't look like existing endpoints have been updated. It would be great if I could get associated projects via a `project_ids` property from within these endpoints.

There is likely more but these are just some initial limitations I found.

**Comment by KonradPaluch** [comment]
Hey! Thank you for the useful feedback, we’ve taken it into consideration but right now we don’t have a timeline for further improvements to these endpoints.

**Comment by ziimk** [comment]
Regarding a place to provide further feedback (if it's not directly related to client-nodejs), I recommend our [DevCommunity](https://devcommunity.pipedrive.com/). Thanks!
