### ISSUE TITLE
File Add Not Working

### ISSUE THREAD

**Issue by dannynelson** [pipedrive/client-nodejs#5]
Hello,

I am having trouble getting the 'Files Add'  to work on the Pipedrive API. 

My server is setup with Express using the connect bodyParser like so.

``` javascript
app.use(express.bodyParser({ keepExtensions: true, uploadDir: 'uploads' }));
```

I submit a POST request to /submit with form data containing a file called 'myFile', and the user email in the query string. The request is sent as 'multipart/form-data encoding', and received successfully.

Pipedrive's client-nodejs is setup like this. 

``` javascript
app.post('/submit', function(request, response) {
  var url_parts = url.parse(request.url, true);
  var email = url_parts.query.email;

  pipedrive.SearchResults.field({
    term: email,
    exact_match: '0',
    field_type: 'personField',
    field_key: 'email',
    return_item_ids: '1'
  }, function(err, data) {
    pipedrive.Files.add({
      file: request.files.myFile,         // Something wrong here
      person_id: data[0].id
    }, function(err, data) {
      response.send(data);
    });
  });

});
```

Everything works until I get to the Files.add section, then I receive this error:

`Error: Pipedrive API error:No files were provided with the request.`

Any ideas what might be the issue?

Thank you for your help!

Danny

**Comment by alexandremaeda** [comment]
@dannynelson, I did the same to you, but for some reason, the files are broken when I try to access through the dashboard.
Support says it currently only works if you manually upload.

**Comment by HriBB** [comment]
I'm having the same problem. Files uploaded to pipedrive via API are broken. What is the solution?

**Comment by celso** [comment]
Same problem here. Uploaded files are corrupted once in pipedrive.
