### ISSUE TITLE
Issue With Documentation of ActivityResponseObject

### ISSUE THREAD

**Issue by vinayakBharadwaj1** [pipedrive/client-nodejs#501]
The documentation for the Pipedrive Node.js client library indicates that the response fields in the ActivityResponseObject are in camelCase, but the actual response uses snake_case for all fields.

Affected Module/Client Library:
Node.js client library for Pipedrive

Affected Endpoint:
Endpoint: /v1/activities

Fields in Question:
All fields in the ActivityResponseObject

Actual Response:
All fields in the actual response are in snake_case.

Expected Behavior:
The documentation for the Node.js client library should accurately represent the case of the response fields to avoid confusion for developers integrating with the API.

Additional Information:

Client Library Documentation Link: [https://github.com/pipedrive/client-nodejs/blob/master/docs/ActivitiesApi.md#getActivities]
Response Documentation Link: [https://github.com/pipedrive/client-nodejs/blob/master/docs/ActivityResponseObject.md]

**Comment by florolf1** [comment]
This is also the case with every RequestObject. Typescript doesn't really work either. I see no advantage in using the NodeJS client. Version 22.5 is now available and it still doesn't work. It's quicker to write your own client...

**Comment by siirimangus** [comment]
Hey, @vinayakBharadwaj1, the documentation issue is now fixed in v22.9.0. Thank you for noticing and reporting!

@florolf1 , could you please open a separate issue for the "Typescript doesn't really work either." and elaborate more about the problem you are facing.
