### ISSUE TITLE
Throwing errors and good practices

### ISSUE THREAD

**Issue by fpirsch** [pipedrive/client-nodejs#502]
The lib throws custom objects instead of `Error` objects, so we don't have the stack trace and logging can't be standardized.
It is considered good practice to throw only instances of the Error class or its subclasses.

https://eslint.org/docs/latest/rules/no-throw-literal
https://rules.sonarsource.com/typescript/RSPEC-3696/

Custom exceptions should extend the native `Error` function.

**Comment by youssef-saber-3** [comment]
Hey , we've updated error handling in the next [beta](https://www.npmjs.com/package/pipedrive/v/22.3.1-rc.3) version of the sdk ,as well as adding typescript support in this version. you can follow the [guide](https://github.com/pipedrive/client-nodejs/blob/typescript-rc/migration.md) here for setup and feel free to give feedback or report any issues you run into

**Comment by fpirsch** [comment]
22.3.1-rc3 still throws intances of custom classes, not native `Error`s

**Comment by Reivilo85k** [comment]
Hi @fpirsch, could you give us some examples of such errors please ?

**Comment by fpirsch** [comment]
Hi @Reivilo85k I was referring to `FailResponseException.js`, `NotFoundException.js`, `OAuthProviderException.js`, `UnauthorizedException.js`
