### ISSUE TITLE
Bulk add

### ISSUE THREAD

**Issue by justemoilouise** [pipedrive/client-nodejs#53]
is it possible to have a bulk add of objects?

**Comment by tot-ra** [comment]
hi @justemoilouise , unfortunately no.

Our backend needs limited request size to respond in predictable time and at the same time we have rate limiting to avoid abuse from clients to also provide predictable response rate to everyone.

So alternatives would be
- import objects serially, taking rate limit into account
- if you have direct access to UI, you can import data from excel
- if you want to integrate multiple services, you could look into https://zapier.com too
