### ISSUE TITLE
Accessing Deal Flow (Updates)

### ISSUE THREAD

**Issue by ps84** [pipedrive/client-nodejs#54]
Sorry if I've missed something obvious but I'm not sure how to access the Deal Flow (Update) data using the API.  The REST API doc list the following call;

List updates about a deal
get /deals/{id}/flow

Thanks for your help.

ps.

**Comment by ps84** [comment]
I see that there is a /updates which still seems to be supported by the REST API (albeit undocumented).  I can use this but I'm concerned that it will be deprecated at some point.  Am I better off using getUpdates() or modifying the blueprints to support flow as a relatedObject of deal?

Is this still API actively supported or should I be looking at an alternative framework for making REST calls?

Thanks again,

ps.

**Comment by tot-ra** [comment]
Hi @ps84, we have changed the endpoint in version 4.0.0 in this PR https://github.com/pipedrive/client-nodejs/pull/64
Take a look and your feedback is welcome
