### ISSUE TITLE
Unable to Retrieve More Than 100 Pipelines with getPipelines Function

### ISSUE THREAD

**Issue by antlaht86** [pipedrive/client-nodejs#577]
## Package: pipedrive client-nodejs (npm: pipedrive)
Version: 23.4.1

## Description:
I'm experiencing an issue with the getPipelines function in the pipedrive package. Specifically, it's not possible to retrieve more than 100 pipelines.

Steps to Reproduce:

Use the getPipelines function with options for pagination, such as start or limit.
Try to set the start parameter to a value greater than 100.
Observe that it is possible to get a maximum of only one hundred items, despite the request's options
## Expected Behavior:
I expect the getPipelines function to respect the provided start and limit parameters, allowing retrieval of more than 100 pipelines when specified.

## Actual Behavior:
The function returns only up to 100 pipelines regardless of the limit value or the start parameter provided in the request.

## Environment:

Node.js version: v20.12.2
Package version: 23.4.1

**Comment by dmitriyeff** [comment]
Hello @antlaht86 ,

Currently, client-nodejs supports only API v1, which does not accept [additional parameters](https://github.com/pipedrive/client-nodejs/blob/master/docs/PipelinesApi.md#getpipelines) and has a limit of 100 pipelines per request.

We’re planning to add support for both v1 and v2 this year, with API v2 increasing the pipeline limit to a maximum of 500.

**Comment by dmitriyeff** [comment]
Hello @antlaht86 ,

Currently, client-nodejs supports only API v1, which does not accept [additional parameters](https://github.com/pipedrive/client-nodejs/blob/master/docs/PipelinesApi.md#getpipelines) and has a limit of 100 pipelines per request.

We’re planning to add support for both v1 and v2 this year, with API v2 increasing the pipeline limit to a maximum of 500.

**Comment by antlaht86** [comment]
Hi!

My problem was that our client has over 100 pipelines, and when we fetch all of them from the Pipedrive API with the Pipedrive SDK, the SDK does not return information that there are still some left (more_items_in_collection)

But if I managed to fix the situation by using Node's Fetch API

```
await fetch(
`https://api.pipedrive.com/v1/pipelines?start=${opts.start}&limit=${opts.limit}`,
);
```

and here more_items_in_collection is true when there are over 100 pipelines and everything works.

So there is some problem with the SDK ?
