### ISSUE TITLE
Event listeners broken

### ISSUE THREAD

**Issue by Thaddaway** [pipedrive/client-nodejs#58]
It appears that the Ad hoc event listeners have stopped working. I'm pretty sure that the problem isn't on my end because even the examples file live-updates.js won't fire the pipedrive.on('connect' event or the pipedrive.on('deal.added' event. No event listeners at all are working, but things like pipedrive.Deals.getAll() still work fine. Does pipedrive still support this client?

**Comment by Thaddaway** [comment]
If anyone is able to use event listeners successfully right now please tell me so I know it's actually on my end if it is! Thanks.

**Comment by arthurjdam** [comment]
The "push notifications" API (which [channel.js](https://github.com/pipedrive/client-nodejs/blob/master/lib/channel.js) relies on) has been deprecated:
https://developers.pipedrive.com/docs/api/v1/#!/PushNotifications/post_pushNotifications
Webhooks will have to be used instead.

**Comment by Thaddaway** [comment]
I see. Thanks for the info!
