### ISSUE TITLE
Live updates not working 

### ISSUE THREAD

**Issue by gabrielsr** [pipedrive/client-nodejs#59]
Tried the example passing my apiKey and it never reach the connected event.

https://github.com/pipedrive/client-nodejs/blob/master/examples/live-updates.js

In debug is possible to see that the it was not possible to connect with server channel.piperdrive.com/socketjs. I'm wondering if this service is still active.

**Comment by martintajur** [comment]
Hi @gabrielsr , implemented a fix for this in a separate pull request (#60). Once that gets merged in, it will work again as expected. It has been one of the experimental beta features of the client so for. However it should be more straightforward going forward.
