### ISSUE TITLE
getAll('Organizations') Not working on NodeJS v6.10.2

### ISSUE THREAD

**Issue by rohit12sh** [pipedrive/client-nodejs#63]
NodeJS: v6.10.2
OS: macOS Sierra 10.12.3 (16D32)
Pipedrive:     "pipedrive": "^3.0.2"

This is the error I am getting when using this module to get All organization:

=== JS stack trace =========================================

Security context: 0x14c3659cfb39 <JS Object>
    1: /* anonymous */(aka /* anonymous */) [/Users/RSharma/leadgen/mean_stack/leadgen/node_modules/pipedrive/lib/Pipedrive.js:93] [pc=0x20e6127640b9] (this=0x14c365904381 <undefined>,err=0x14c365904201 <null>,models=0x3d9bb9e05691 <JS Array[100]>)
    2: arguments adaptor frame: 5->2
    3: /* anonymous */(aka /* anonymous */) [/Users/RSharma/leadgen/mean_stack/leadgen/node_modules/pipedrive/l...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/RSharma/.nvm/versions/node/v6.10.2/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/RSharma/.nvm/versions/node/v6.10.2/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/RSharma/.nvm/versions/node/v6.10.2/bin/node]
 4: v8::internal::Factory::NewUninitializedFixedArray(int) [/Users/RSharma/.nvm/versions/node/v6.10.2/bin/node]
 5: v8::internal::Factory::NewJSArrayStorage(v8::internal::Handle<v8::internal::JSArray>, int, int, v8::internal::ArrayStorageAllocationMode) [/Users/RSharma/.nvm/versions/node/v6.10.2/bin/node]
 6: v8::internal::Factory::NewJSArray(v8::internal::ElementsKind, int, int, v8::internal::ArrayStorageAllocationMode, v8::internal::PretenureFlag) [/Users/RSharma/.nvm/versions/node/v6.10.2/bin/node]
 7: v8::internal::ElementsAccessor::Concat(v8::internal::Isolate*, v8::internal::Arguments*, unsigned int) [/Users/RSharma/.nvm/versions/node/v6.10.2/bin/node]
 8: v8::internal::(anonymous namespace)::Fast_ArrayConcat(v8::internal::Isolate*, v8::internal::Arguments*) [/Users/RSharma/.nvm/versions/node/v6.10.2/bin/node]
 9: v8::internal::Builtin_Impl_ArrayConcat(v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)0>, v8::internal::Isolate*) [/Users/RSharma/.nvm/versions/node/v6.10.2/bin/node]
10: v8::internal::Builtin_ArrayConcat(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/RSharma/.nvm/versions/node/v6.10.2/bin/node]
11: 0x20e611c092a7

And this is my code:
`
const Pipedrive = require('pipedrive');

const pipedriveCl = new Pipedrive.Client(pipedriveConstants.pipedriveAPIToken, { strictMode: true });

 pipedriveCl.getAll('Organizations', function (err, collection) {
        res.json({
            success: true,
            data: collection
        }) 
    })
`

**Comment by tot-ra** [comment]
hi @rohit12sh, tried out your code with 6.10.2, cannot reproduce it. 
Can you tell what res.json does?
I guess «Allocation failed - JavaScript heap out of memory» means that your process does not have enough memory. Can you debug how much data you receive?

**Comment by eerootsus** [comment]
Closing this issue as there is no response from the initial reporter. And it's quite likely the organisation list was large and not enough resources available for the process, as indicated by the out of memory error.
