### ISSUE TITLE
Make UserAgent configurable

### ISSUE THREAD

**Issue by pcothenet** [pipedrive/client-nodejs#66]
Currently, UserAgent defaults to a os + version + has value:

- https://github.com/pipedrive/client-nodejs/blob/master/lib/rest.js#L95
- https://github.com/pipedrive/client-nodejs/blob/master/lib/userAgent.js

Would it be possible to let the user overwrite this value in the `options` object?

(We at MadKudu have a Pipedrive integration and your internal team has asked us if we could modify the User-Agent header so calls coming from MadKudu are easily identifiable)

**Comment by eerootsus** [comment]
Closing this issue as the related PR was closed early in the year. Very likely this issue is no longer relevant to the reporter.

**Comment by gregarican** [comment]
Speaking of UserAgent values, what value is sent from PipeDrive when it syncs with Office 365? I administer our company's tenant org and see risky sign-in alerts for O365 account access. The IP's are all Amazon EC2 instances, so I'm in the dark there. The UserAgent value comes back as "python-EAS-Client 1.0." Is that what PipeDrive uses on their end?

**Comment by eerootsus** [comment]
@gregarican 
O365 sync with Pipedrive is actually performed by Nylas and indeed they are using `python-EAS-Client 1.0` as their user agent. https://docs.nylas.com/docs/suggested-office-365-settings

But this question is in no way related to this NodeJS library, so if you have any further issues, please contact our support or try our dev community https://devcommunity.pipedrive.com/
