### ISSUE TITLE
How do i make it work with angular 2 only!

### ISSUE THREAD

**Issue by DeepakTivari** [pipedrive/client-nodejs#70]
I can't find any type definition that will allow the pipedrive API to work with angular 2 / without nodejs

**Comment by tot-ra** [comment]
@DeepakTivari this is nodejs library only (thus the naming) and there is no official browser client js library (and thus specifically angular). You could opensource your library so that its mentioned in https://developers.pipedrive.com/ or you could add pull request

**Comment by eerootsus** [comment]
Closing this issue as the initial question has been answered a long time ago.

**Comment by maxime1992** [comment]
The first error I had when trying to use the SDK in the browser was that Buffer is missing so I had hope it'd be the only one and tried using the Buffer polyfill: https://www.npmjs.com/package/buffer

But no luck I got a bunch of other errors after that so I'll just use the API.

It'd be nice to have this supported directly in the browser as the SDK handles (I believe) token refresh etc...
