### ISSUE TITLE
Automatic rate limiting

### ISSUE THREAD

**Issue by super-cache-money** [pipedrive/client-nodejs#73]
This would be so cool! It'd be super easy to stay under pipedrive limits. And also not that hard, I think.

Maybe there's an option where you can set the rate limit for all API requests.

**Comment by super-cache-money** [comment]
I wrapped it myself with https://github.com/jhurliman/node-rate-limiter , works great

**Comment by eerootsus** [comment]
Closing this issue - it's a neat request, but as requirements of every client library consumer is very specific and there are many other libraries to achieve this (as the OP stated themselves), there doesn't seem enough interest at this time.
