### ISSUE TITLE
{Object}.save not working

### ISSUE THREAD

**Issue by super-cache-money** [pipedrive/client-nodejs#74]
Here's what I'm trying to do:

```
const Pipedrive = require('pipedrive');
const pipedrive = new Pipedrive.Client('mykey', { strictMode: true });
pipedrive.Deals.get(123, function(err, deal){
  console.log("Got deal :)", deal);
  deal.set("title", "LOOOL");
  deal.save(function(err, out) {
    if (err) return console.log(err);
    console.log("saved :)", out);
  });
});
```

And that throws the following error:
```
> TypeError: Cannot read property 'id' of null
    at doWrap (/path/to/project/node_modules/pipedrive/lib/wrapCollectionItems.js:12:21)
    at /path/to/project/node_modules/pipedrive/lib/wrapCollectionItems.js:37:5
    at Function.forEach (/path/to/project/node_modules/pipedrive/node_modules/lodash/dist/lodash.js:3298:15)
    at wrapCollectionItems (/path/to/project/node_modules/pipedrive/lib/wrapCollectionItems.js:36:6)
    at /path/to/project/node_modules/pipedrive/lib/CollectionItem.js:26:27
    at RestHandlers.genericResponse (/path/to/project/node_modules/pipedrive/lib/restHandlers.js:79:3)
    at Request.<anonymous> (/path/to/project/node_modules/pipedrive/lib/restHandlers.js:171:9)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/path/to/project/node_modules/pipedrive/lib/rest.js:131:16)
```

I have tested really extensively and everything else I'm trying to do works perfectly well...

**Comment by tot-ra** [comment]
@super-cache-money Did you get "Got deal" in console? I think you don't have deal with id 123, so you can't save it

**Comment by JohannesHome** [comment]
Hey, this issue occurs for me when doing `pipedrive.Deals.get` on a deleted deal. The `item` passed into `wrapCollectionItems.js:12:21` is null, and hence has no `item.id`. 

I would prefer an empty collection for this case, as it allows us to handle the not found case. 

Can you fix this?

**Comment by super-cache-money** [comment]
Yup it was a deleted deal for me. The error did confuse & immobilise us, so
fixing that would be great.

**Comment by JohannesHome** [comment]
As a follow up. I was able to reproduce the issue finally, and the delete was unrelated to my problem but a http error of `4xx` group as this issue relates to. 

We basically have a situation where we do a `object.save(handler)` call when nothing was changed in the object. In this case the client is doing a `put` with an empty object `{}` as no value has changed, and the server response with `400`. 

The main issue is, therefore, that [save](https://github.com/pipedrive/client-nodejs/blob/768fe160103cb5537c5e4266de5f58f4ab40241e/lib/CollectionItem.js#L25-L28), [merge](https://github.com/pipedrive/client-nodejs/blob/768fe160103cb5537c5e4266de5f58f4ab40241e/lib/CollectionItem.js#L43-L46) and [duplicate](https://github.com/pipedrive/client-nodejs/blob/768fe160103cb5537c5e4266de5f58f4ab40241e/lib/CollectionItem.js#L43-L46) do not propagate the error to the handler, but instead try to access `data`. All these functions generate the same mentioned error in case the server response with anything else besides `200` containing an empty body.

This should be easy to fix.

**Comment by vasiabikeru** [comment]
I have the same issue with the following:

`console.log("initial:` ", person["First Name"]); // output: undefined
            person.set("First Name", firstName);
            person.set("Last Name", lastName);
            console.log("saved: ", person["First Name"]); // output: Bradley
            person.save(function(err) { console.log("error", err); });`

result is:

`..../node_modules/pipedrive/lib/wrapCollectionItems.js:12
			var itemId = item.id || false;
			                  ^

TypeError: Cannot read property 'id' of null
    at doWrap (..../node_modules/pipedrive/lib/wrapCollectionItems.js:12:22)
    at ..../node_modules/pipedrive/lib/wrapCollectionItems.js:37:5`

**Comment by jonathanstokes** [comment]
Still seeing the problem @JohannesHome mentions.  When running within Node, hitting this kind of error in any call causes Node to crash, with no chance to intercept in a try/catch or callback.

**We can't use this library because of this problem.**
