### ISSUE TITLE
Support async/await & promises

### ISSUE THREAD

**Issue by one000mph** [pipedrive/client-nodejs#81]
I'd like to use this in a node 10 app with async/await, but as is I would need to use callback syntax.

**Comment by tot-ra** [comment]
This lib would need a significant rewrite to support that. 
@ziimk and team is considering that, no ETAs or roadmap yet

**Comment by MelMacaluso** [comment]
@tot-ra any news on the async/wait version? 😢

**Comment by one000mph** [comment]
I'm currently using `async/await` calls with this library with a simple wrapper function. It's pretty easy to transform a callback format with the existing `Promise`object class. Hope this helps others who are still "awaiting" 😆  `async/await`

My api framework is hapi so logging happens with using `request.log` 

```
# lib/wrappers/pipedrive.js
const OriginalPipedrive = require('pipedrive');
const Config = require('getconfig');

const { isDev } = Config.getconfig;
const apiToken = Config.pipedrive.token;

const Pipedrive = function (token) {

  if (!isDev) {
    this.pipedrive = new OriginalPipedrive.Client(token, { strictMode: true });
  }
};

Pipedrive.prototype.getPerson = function (id, request) {

  if (this.pipedrive) {

    return new Promise((resolve, reject)  => {

      return this.pipedrive.Persons.get(id, (err, person) => {

        if (err !== null) {
          request.log(['error', 'pipedrive'], 'Could not get Person: ' + id);
          reject(err);
          return;
        }

        resolve(person);
        return;
      });
    });
  }
};
```

In another file
```
const Pipedrive = require('./lib/wrappers/pipedrive');


## inside handler so we have `request` defined
const person = await Pipedrive.getPerson(id, request);
```

**Comment by MelMacaluso** [comment]
@one000mph thanks a lot for the wrapper indeed, I like it. Still OTB so we can avoid writing that in our codebase would be even cooler ahah.

**Comment by enzoferey** [comment]
If somebody is looking for an abstracted version of what @one000mph suggested:

```js
function promiseWrapper(apiCall, payload) {
  return new Promise((resolve, reject) => {
    return apiCall(payload, (error, resource) => {
      if (error !== null) {
        reject(error);
        return;
      }
      resolve(resource);
      return;
    });
  });
}
```

You can later use it as:

```js
const dealPayload = { ... };
const createdDeal = await promiseWrapper(PipedriveClient.Deals.add, dealPayload);
```

**Comment by one000mph** [comment]
I would have some time in the next week or so to add my wrapper to this lib if that's something you wanted to pursue @tot-ra. I haven't contributed to this repo before so lmk if there's any rules or conventions I should look at.

**Comment by kopax** [comment]
Thanks @one000mph that's a good move for JS developer who want to use pipedrive. 

You should maybe try to contact them by email first if you want to get a fast answer, they look not to check here often.

I will have a development that include pipedrive integration in the next few weeks, in case you do it before can I please subscribe to the repo to see the development progress, even if it's not integrated on this official branch, I may use it if it's released on time for my development, otherwise, I'll pick the cb version and upgrade later.

**Comment by tot-ra** [comment]
My vision is to have library support promises natively, without using callbacks (so it would be a breaking change with major release), thats why I wrote that it would need a significant rewrite. Sure, you use wrappers for now.

If you make a PR and don't get review in timely manner, you can:
- ask https://devcommunity.pipedrive.com/
- ask support to escalate an issue
- contact @gutiju , @ziimk team
- ask https://twitter.com/PipedriveDev/

**Comment by MelMacaluso** [comment]
To be honest with you guys I like @enzoferey version more, straight to the point and usable in most cases...

There's an edge case which needs a small rewrite (when invoking a method from ie. `pipedrive.Deals.get response` such as: `deal.addFollowers()` because for some unknown reason (flaw in the wrapper design?) it takes an id *and* a payload 😂 . 

A small verbose quick rewrite to handle also that edge case would be:

```
const promiseWrapper = (apiCall, id, payload) => {
  return new Promise((resolve, reject) => {
    if(id) {
      return apiCall(id, payload, (error, resource) => {
        if (error) {
          reject(error)
        }
        resolve(resource)
      })
    }
    return apiCall(payload, (error, resource) => {
      if (error) {
        reject(error)
      }
      resolve(resource)
    })
  })
}
```

**Comment by kopax** [comment]
If someone publishes a community library that works with `async/await` until Stripe implements it, let us know here.

**Comment by enzoferey** [comment]
Is `Stripe` working on an implementation at the moment ? How long do you think it will take to them to release it ?

**Comment by kopax** [comment]
@enzoferey they currently does not seems to want to support the feature at the moment. You can try to contact them and ask your question using their communication channel, see https://github.com/pipedrive/client-nodejs/issues/81#issuecomment-549260130

**Comment by RuTsEST** [comment]
Async/await is now supported as of version 10. #111

**Comment by kopax** [comment]
Wow excellent thanks a lot @RuTest that was unexpected and quick. Thanks for approving this feature request. I am still looking to integrate pipedrive with react-native components (such as [`react-native-paper`](https://callstack.github.io/react-native-paper), it would be great if you could also help us there. Should I open a new ticket?

**Comment by MelMacaluso** [comment]
Thanks guys! Now buckle up your seatbelts is `refactor time`
