### ISSUE TITLE
ENOENT: no such file or directory, open '//../package.json'

### ISSUE THREAD

**Issue by JohannesHome** [pipedrive/client-nodejs#89]
Not sure if this is a problem for others, but I came accross this when bundling the client using [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack).

Basically the client expects a `package.json` in its root directory from which it fetches the version. 

https://github.com/pipedrive/client-nodejs/blob/09d1a238b63f4d929a8c7c9a239082161d014597/lib/inflection.js#L564-L566

The script is making some assumptions about it's runtime environment that may not be guaranteed. 

Any chance of removing this?

**Comment by vuongngo** [comment]
Have this issue been resolved? I try this library to make integration easier, but it doesn't work with serverless-webpack.

**Comment by perry-mitchell** [comment]
Yes, this is causing me some pain downstream as well. It'd be best to bundle the version into the release some how. I'll see if I can't make a PR for it.
