### ISSUE TITLE
When Persons.add and Deals.add, error is blank

### ISSUE THREAD

**Issue by emafriedrich** [pipedrive/client-nodejs#91]
When Persons.Add and Deals.add fails, the error object is blank.

Code example (typescript):

```
pipedrive.Persons.add(person, async (error: any, person: any) => {
        if (error) {
            logInRollbar('PERSON NOT CREATED', error);
           //...
```

In my rollbar account i recive:

![Screenshot from 2019-03-30 14-52-13](https://user-images.githubusercontent.com/972640/55277028-d5474f00-52fb-11e9-9341-770e8f8f88e6.png)

**Comment by eerootsus** [comment]
@emafriedrich 
Deepest apologies for such a delayed response.

Is this still an issue?

I tried to reproduce, but cannot. Looking at the library code I do see there is a chance an empty object is passed in as an error https://github.com/pipedrive/client-nodejs/blob/master/lib/restHandlers.js#L50 But this is too vague to try to fix from - could be a bug with the underlying library or a mishandled use case.

If this is still relevant can you please try and turn console logging on by setting `PIPEDRIVE_DEBUG=true` in your environment? You should then see details about the requests and responses.

Another option for further digging would be to use the `rawResponse` in the callback (returned as the fifth argument) and check the actual status code. I suspect it is something 4XX or 5XX related.

**Comment by RuTsEST** [comment]
Closing this as there is now an updated version of the client available which does give an appropriate error response.
