### ISSUE TITLE
Typos in the Readme.md 

### ISSUE THREAD

**Issue by frozan** [pipedrive/client-nodejs#97]
- `npm install pipedrive` is not necessary since the dependencies already contain this package. Only `npm install` is sufficient

- `npm run tests` should be changed to `npm run test`

- The `npm run test` gives error on the Windows platform because of the path 
(/) issues. The proposed solution is: 
`"scripts": {
    "test:unx": "./node_modules/mocha/bin/mocha ./test/unit",
    "test:win": "node node_modules\\mocha\\bin\\mocha .\\test\\unit"
},`

**Comment by tot-ra** [comment]
I'd say issue with windows needs better approach than another command
